{% set version = "11.2.2" %}

package:
  name: osmesa
  version: {{ version }}

source:
  url: https://github.com/mesa3d/mesa/archive/mesa-{{ version }}.tar.gz
  fn: mesa-v{{ version }}.tar.gz
  sha256: a2edf7ad2589f0c3b5cd3d8f8866193c03bf871a38d5dc27423a03f352abe2de

build:
  number: 0
  # feel free to figure out how to build for other targets and submit a PR
  # instructions here: http://mesa3d.org/install.html
  skip: true  # [not linux]

requirements:
  build:
    - toolchain

test:
  commands:
    - test -f ${PREFIX}/lib/libOSMesa.so  # [unix]

about:
  home: https://github.com/mesa3d/mesa
  license: MIT
  summary: The Mesa 3-D graphics library (an OffScreen rendering build)

extra:
  recipe-maintainers:
    - Korijn
