{% set version = "11.2.2" %}

package:
  name: mesa
  version: {{ version }}

source:
  url: https://github.com/mesa3d/mesa/archive/mesa-{{ version }}.tar.gz
  fn: mesa-v{{ version }}.tar.gz
  sha256: a2edf7ad2589f0c3b5cd3d8f8866193c03bf871a38d5dc27423a03f352abe2de

build:
  number: 0
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain
    - python 2.7.*
    - scons
    - mako
    - flex  # [unix]
    - bison  # [unix]
    - mingwpy  # [win]

about:
  home: https://github.com/mesa3d/mesa
  license: MIT
  summary: The Mesa 3-D graphics library (an OffScreen rendering build)

extra:
  recipe-maintainers:
    - Korijn
