{% set version = "0.3.1" %}

package:
  name: vtku3dexporter
  version: {{ version }}

source:
  fn: vtku3dexporter-v{{ version }}.tar.gz
  url: https://github.com/ClinicalGraphics/u3d/archive/{{ version }}.tar.gz
  md5: c28c1c3f40c7f8c4d7085783daa32444

build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0

requirements:
  build:
  - python
  - cmake 3.5.*
  - u3d 0.2.*
  - vtk 7.0.*
  run:
  - python
  - u3d 0.2.*
  - vtk 7.0.*
  - future

test:
  imports:
  - vtku3dexporter

about:
  home: https://github.com/ClinicalGraphics/u3d
  license: Apache-2.0
  summary: vtkU3DExporter with Python bindings
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
    - EelcoHoogendoorn
