{% set version = "0.2.0" %}

package:
  name: vtku3dexporter
  version: {{ version }}

source:
  path: ..\..\..\u3d\Samples\SampleCode
  #fn: vtku3dexporter-v{{ version }}.tar.gz
  #url: https://github.com/ClinicalGraphics/u3d/archive/{{ version }}.tar.gz
  #md5: 9ed46d04e80a2995abd597ebfb5f788f

build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0
  # VTK 7 is only available on linux x64 py2.7 and py3.5 at the moment
  # will open a PR later when dependencies become available on all platforms
  skip: true  # [osx or linux32 or py34]

requirements:
  build:
  - python
  - cmake 3.5.*
  - u3d >=0.2.0
  - vtk 7.0.*
  run:
  - python
  - u3d >=0.2.0
  - vtk 7.0.*

test:
  imports:
  - vtku3dexporter.VTKU3DExporter

about:
  home: https://github.com/ClinicalGraphics/u3d
  license: Apache-2.0
  summary: VTKU3DExporter with Python bindings
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
    - EelcoHoogendoorn
