{% set version = "0.1.0" %}

package:
  name: vtku3dexporter
  version: {{ version }}

source:
  url: https://github.com/ClinicalGraphics/u3d/archive/vtk7.zip
  fn: vtku3dexporter-v{{ version }}.zip
  sha256: 91843d348b16b3205663a44ea79d2279f2e27a988d40f521d61628746de73b02

build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0
  # dependencies are only available on linux x64, py2.7 and py3.5 at the moment
  skip: true  # [osx or win or linux32 or py34]

requirements:
  build:
  - python
  - cmake 3.5.*
  - u3d
  - vtk 7.*
  run:
  - python
  - u3d
  - vtk 7.*

about:
  home: https://github.com/ClinicalGraphics/u3d
  license: Apache-2.0
  summary: Universal 3D Sample Software VTKU3DExporter and Python bindings
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
    - EelcoHoogendoorn
