{% set version = "0.1.0" %}

package:
  name: vtku3dexporter
  version: {{ version }}

source:
  path: ../u3d/Samples/SampleCode
#  git_url: https://github.com/ClinicalGraphics/vtku3d.git
#  git_tag: {{ version }}

build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0
  skip: true  # [osx or win32 or linux32]

requirements:
  build:
  - python
  - cmake
  - u3d
  - vtk 7.*
  run:
  - python
  - u3d
  - vtk 7.*

about:
  home: https://github.com/ClinicalGraphics/vtku3d
  license: Apache-2.0
  summary: Universal 3D Sample Software
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
    - EelcoHoogendoorn
