{% set version = "0.1.0" %}

package:
  name: vtku3dexporter
  version: {{ version }}

source:
  url: https://github.com/ClinicalGraphics/u3d/archive/{{ version }}-vtk7.tar.gz
  fn: vtku3dexporter-v{{ version }}.tar.gz
  md5: 66da02cb5d2d5156189cdab9c512ee84

build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0
  # dependencies are only available on linux x64, py2.7 and py3.5 at the moment
  # will open a PR later when dependencies becomem available on all platforms
  skip: true  # [osx or win or linux32 or py34]

requirements:
  build:
  - python
  - cmake 3.5.*
  - u3d
  - vtk 7.0.*
  run:
  - python
  - u3d
  - vtk 7.0.*

about:
  home: https://github.com/ClinicalGraphics/u3d
  license: Apache-2.0
  summary: Universal 3D Sample Software VTKU3DExporter and Python bindings
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
    - EelcoHoogendoorn
