{% set version = "0.1.0" %}

package:
  name: vtku3dexporter
  version: {{ version }}

source:
  url: https://github.com/ClinicalGraphics/u3d/archive/vtk7.zip
  fn: vtk7.zip

build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0
  skip: true  # [osx or win32 or linux32]

requirements:
  build:
  - python
  - cmake 3.5*
  - u3d
  - vtk 7.*
  run:
  - python
  - u3d
  - vtk 7.*

about:
  home: https://github.com/ClinicalGraphics/u3d
  license: Apache-2.0
  summary: Universal 3D Sample Software vtk exporter and pyton bindings
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
    - EelcoHoogendoorn
